version: "3.9"
services:
  app:
    build: .
    links:
      - postgres-db
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    restart:
      on-failure
    env_file:
      - .env
    command:
      - "/app/main"
  postgres-db:
    image: postgres:13.3
    restart: unless-stopped
    ports:
        - "5432:5432"
    environment:
        LC_ALL: C.UTF-8
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_HOST: "postgres-db"
    env_file:
      - .env
    volumes:
      - ./migrations/tables.up.sql

